"""
Score external evaluation corpora with the unmodified LLM judge.

Tasks A1 (EvasionBench) and A3 (QEvasion/CLARITY) of the IEEE BigData sprint.

The judge is used exactly as the paper describes it: judge.call_judge, the same
SYSTEM_PROMPT, claude-sonnet-4-6, temperature 0, max_tokens 300. Nothing is
tuned to either external corpus -- that is the point of the exercise. Scores are
produced blind to the external label; the label is only joined afterwards, in
analyse_external.py.

Sampling is fixed by seed and recorded in the output so the run is reproducible.

IMPORTANT -- what these corpora are:
  evasionbench : labels in `eva4b_label` are MODEL-GENERATED by Eva-4B-V2, not
                 human annotation. Their dataset card states this outright. Any
                 agreement measured here is cross-system agreement with a
                 fine-tuned specialist model, NOT external human validation.
  qevasion     : labels ARE human, from three independent annotators, on U.S.
                 political interviews -- a genuinely different domain from
                 earnings calls.

Resumable: existing rows in the output CSV are skipped, so a crash or an
interrupted run costs nothing already paid for.

Usage:
    python src/score_external.py --dataset evasionbench --n 1000
    python src/score_external.py --dataset qevasion            # all 308
"""

import argparse
import os
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "src"))

EXTERNAL_DIR = BASE_DIR / "data" / "external"
RESULTS_DIR = BASE_DIR / "results"
DIMS = ["non_responsiveness", "vagueness", "deflection", "hedging"]

# How to read each corpus: (file, id column, question column, answer column,
# label column carried through for the later join).
SPECS = {
    "evasionbench": {
        "path": EXTERNAL_DIR / "evasionbench_full.parquet",
        "id": "uid",
        "question": "question",
        "answer": "answer",
        "label": "eva4b_label",
    },
    "qevasion": {
        "path": EXTERNAL_DIR / "qevasion_test.csv",
        "id": "index",
        "question": "interview_question",
        "answer": "interview_answer",
        "label": "clarity_label",
    },
}


def load_dotenv():
    """Read .env into os.environ. .env is gitignored; never commit a key."""
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())


def load_corpus(name, n, seed):
    spec = SPECS[name]
    path = spec["path"]
    if not path.exists():
        raise SystemExit(f"{path} not found -- run the download step first.")
    df = pd.read_parquet(path) if path.suffix == ".parquet" else pd.read_csv(path)

    df = df[[spec["id"], spec["question"], spec["answer"], spec["label"]]].copy()
    df.columns = ["ext_id", "question_text", "response_text", "ext_label"]
    df = df.dropna(subset=["question_text", "response_text"]).reset_index(drop=True)

    if n and n < len(df):
        # Uniform random, prevalence-preserving. AUROC is prevalence-invariant,
        # and keeping the natural class balance is what makes Macro-F1 and
        # weighted kappa comparable to the numbers the corpus authors report.
        df = df.sample(n=n, random_state=seed).reset_index(drop=True)
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True, choices=sorted(SPECS))
    ap.add_argument("--n", type=int, default=None, help="sample size (default: all)")
    ap.add_argument("--seed", type=int, default=20260819)
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()

    load_dotenv()
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("ANTHROPIC_API_KEY not set (checked environment and .env)")

    import anthropic
    import judge

    RESULTS_DIR.mkdir(exist_ok=True)
    out_csv = RESULTS_DIR / f"external_scores_{args.dataset}.csv"

    df = load_corpus(args.dataset, args.n, args.seed)

    done = set()
    prior = []
    if out_csv.exists():
        old = pd.read_csv(out_csv)
        prior = old.to_dict("records")
        done = set(old["ext_id"].astype(str))
        print(f"Resuming: {len(done)} rows already scored in {out_csv.name}")

    todo = [r for r in df.to_dict("records") if str(r["ext_id"]) not in done]
    print(f"Corpus: {args.dataset}  |  sampled {len(df)}  |  to score {len(todo)}")
    print(f"model={judge.MODEL} temperature={judge.TEMPERATURE} "
          f"max_tokens={judge.MAX_TOKENS} seed={args.seed} workers={args.workers}")
    print(f"label distribution in sample: "
          f"{df['ext_label'].value_counts().to_dict()}\n")
    if not todo:
        print("Nothing to do.")
        return

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    lock = threading.Lock()
    rows = list(prior)
    counters = {"ok": 0, "fail": 0}
    t0 = time.time()

    def work(r):
        s = judge.call_judge(client, r["question_text"], r["response_text"])
        score = ((sum(s[d] for d in DIMS) / 4) - 1) / 4 * 100
        return {
            "ext_id": r["ext_id"],
            "ext_label": r["ext_label"],
            **{d: s[d] for d in DIMS},
            "evasion_score": round(score, 2),
            "primary_evasion_type": s["primary_evasion_type"],
            "rationale": s["rationale"],
            "judge_model": judge.MODEL,
        }

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futs = {pool.submit(work, r): r for r in todo}
        for i, fut in enumerate(as_completed(futs), 1):
            try:
                rec = fut.result()
            except Exception as exc:
                with lock:
                    counters["fail"] += 1
                print(f"  [{i}/{len(todo)}] FAILED id={futs[fut]['ext_id']}: {exc}")
                continue
            with lock:
                rows.append(rec)
                counters["ok"] += 1
                if counters["ok"] % 50 == 0:
                    pd.DataFrame(rows).to_csv(out_csv, index=False)
                    rate = counters["ok"] / (time.time() - t0)
                    print(f"  [{i}/{len(todo)}] checkpoint {len(rows)} rows | "
                          f"{rate:.1f} pairs/s | "
                          f"mean evasion={pd.DataFrame(rows)['evasion_score'].mean():.1f}")

    pd.DataFrame(rows).to_csv(out_csv, index=False)
    elapsed = time.time() - t0

    print("\n" + "=" * 62)
    print(f"scored this run : {counters['ok']}")
    print(f"failed          : {counters['fail']}")
    print(f"total in file   : {len(rows)}")
    print(f"wall clock      : {elapsed/60:.1f} min "
          f"({counters['ok']/max(elapsed,1e-9):.2f} pairs/s at {args.workers} workers)")
    print(f"output          : {out_csv}")
    print("=" * 62)


if __name__ == "__main__":
    main()
